calportal/urls.py
from django.urls import path
from . import views 
  
# importing views from views..py
from .views import *

app_name='cal'

urlpatterns = [
    path('280/', DataCreateView.as_view(), name='Datacreate' ),
    path('391/', DataListView.as_view(), name='DataList' ),
]

home/urls.py
from django.urls import path

from . import views

app_name= 'reg' 
urlpatterns = [
	path('',views.regs,name=''),
	path('spouse/',views.further,name='spouse'),
	path('child/',views.studs,name='child'),
	path('thanks/', views.thanks, name='success'),
	path('pay/', views.pay, name='pay'),

]

proface/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

import professional

urlpatterns = [
    path('das/', include('dashboard.urls')),
    path('', include('professional.urls')),
    path('home/',include('home.urls')),
    path('cal/',include('calportal.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns=urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

calportal/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class caldir(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name=models.CharField(max_length=40)
    jobsector=models.CharField(max_length=40)
    phone=models.BigIntegerField()
    panchayat=models.CharField(max_length=40)
    reg_status=models.CharField(max_length=50)
    pr_status=models.CharField(max_length=50)

    def __str__(self):
        return self.name

calportal/forms.py
from django import forms
from django.forms import fields, widgets
from .models import * 
from collections import OrderedDict
from django.contrib.auth.models import User

REG_CHOICE=(
    ('NOTHING','NOT REGISTERED'),
    ('ALONE','REGISTERED ALONE'),
    ('FAMILY','REGISTERED WITH FAMILY'),
    ('FRIENDS', 'REGISTERED WITH FRIENDS'),
    ('ONLINE', 'REGISTERED BUT VIEW ONLINE'))

PR_CHOICE=(
    ('INSTALLED','INSTALLED'),
    ('NOT','NOT INSTALLED'),
    ('ALREADY', 'ALREADY INSTALLED'))

class calform(forms.ModelForm):
    class Meta:
        model=caldir
        fields=['name', 'jobsector', 'phone', 'panchayat','reg_status', 'pr_status']
        labels={
            'name':'NAME',
            'jobsector' : 'JOB SECTOR',
            'phone':'PHONE',
            'panchayat':'PANCHAYAT/MUNICIPALITY',
            'reg_status':'REGISTRATION STATUS',
            'pr_status':'PEACE RADIO STATUS',

        }
        widgets={
            'reg_status':forms.Select(choices= REG_CHOICE), 
            'pr_status':forms.Select(choices = PR_CHOICE),
            }
        
        # field_order={'name', 'jobsector', 'phone', 'panchayat','reg_status', 'pr_status'}

 

class calstat(forms.ModelForm):
    class Meta:
        model=caldir
        fields={'reg_status', 'pr_status'}
        widgets={
            'reg_status':forms.Select(choices= REG_CHOICE), 
            'pr_status':forms.Select(choices = PR_CHOICE),
        }
class dash(forms.ModelForm):
    class Meta:
        model = caldir
        fields={'name', 'jobsector', 'phone', 'panchayat','reg_status', 'pr_status'}

calportal/views.py
from django import forms
from django.forms import fields
from django.http import request
from django.shortcuts import redirect, render
from django.views.generic import CreateView
from django.views.generic.edit import UpdateView
from .forms import calform, calstat, dash
from .models import caldir
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User,auth
from django.views.generic.list import ListView


class DataCreateView(LoginRequiredMixin, CreateView):
    login_url='pro:log'

    model = caldir
    form_class = calform
    template_name = 'calportal/enter.html'
    # fields = ['name', 'jobsector', 'phone', 'panchayat', 'reg_status', 'pr_status']

    def post(self, request, *args, **kwargs):
        caldata=calform(request.POST)
        if caldata.is_valid():
            cal = caldata.save(commit=False)
            cal.user = request.user
            cal.save()
        return redirect('cal:DataList')

class DataListView(LoginRequiredMixin, ListView):
    login_url='pro:log'

    model = caldir
    paginate_by = 30
    template_name='calportal/listing.html'

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)
 

calportal/templates/calportal/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>WISDOM YOUTH DATA</title>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <h2 class="mt-2">CALLING PORTAL</h2>
          <hr class="mt-0 mb-4">
          {% block content %}
          
          {% endblock %}
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>
</html>

calportal/templates/calportal/enter.html
{% extends 'calportal/base.html' %}

{% block content %}
<table>
  <form method="post">
    {% csrf_token %}
    {{ form.as_table }}</table>

    <button type="submit" class="btn btn-success"> SAVE DATA </button>
    <a href="{% url 'cal:DataList' %}"><button type="button" class="btn btn-success">CANCEL</button></a>
  </form>
{% endblock %}

calportal/templates/calportal/listing.html
{% extends 'calportal/base.html' %}

{% block content %}

<a href="{% url 'cal:Datacreate' %}"><button type="button" class="btn btn-success">ADD NEW PERSON</button></a>
<div class="table-responsive-xxl">
<table class="table">
    <thead class="table-dark">
    <tr>
        <!-- <th>SL NO.</th> -->
        <th>NAME</th>
        <th>JOB_SECTOR</th>
        <th>LOCATION</th>
        <th>REG_STATUS</th>
    </tr>
    </thead>
    <!-- Iterate over object_list -->
    {% for object in object_list %}

    <!-- Display Objects -->
   <tbody>
    <tr>
        
        <td><a href="{{object.get_absolute_url}}">{{ object.name }}</a></td>
        <td>{{ object.jobsector }}</td>
        <td>{{ object.panchayat }}</td>
        <td>{{ object.reg_status }}</td>
    </tr>
    </tbody>
    


  
    <!-- If objet_list is empty  -->
    {% empty %}
    <li>No entries yet, please add new entry</li>
    {% endfor %}
</table>
</div>
{% endblock %}

calportal/templates/calportal/login.html
{% extends 'calportal/base.html' %}

{% block content %}
<!-- <div>
  <a href="upi://pay?pa=wisdomislamiorganzization@sbi&amp;pn=PROFACE TEAM&amp;cu=INR" class="upi-pay1">

   <input type="button" name="next" class="register" value="PAY REGISTRATION FEE"></a>
</div> -->
  <form action= {% url 'cal:login' %} method="post">
    {% csrf_token %}
    <div>
      <input type="tel" name="phone" id="phone" class="input-text" placeholder="Phone Number">
    </div>

    <button type="submit" class="btn btn-success">Enter</button>
  </form>
{% endblock %}