calportal/urls.py
from django.urls import path
from . import views 
  
# importing views from views..py
from .views import *

app_name='cal'

urlpatterns = [
    path('280/', DataCreateView.as_view(), name='Datacreate' ),
    path('391/', DataListView.as_view(), name='DataList' ),
]

home/urls.py
from django.urls import path

from . import views

app_name= 'reg' 
urlpatterns = [
	path('',views.regs,name=''),
	path('spouse/',views.further,name='spouse'),
	path('child/',views.studs,name='child'),
	path('thanks/', views.thanks, name='success'),
	path('pay/', views.pay, name='pay'),

]

proface/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

import professional

urlpatterns = [
    path('das/', include('dashboard.urls')),
    path('', include('professional.urls')),
    path('home/',include('home.urls')),
    path('cal/',include('calportal.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns=urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

professional/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'pro'

urlpatterns = [
	path('987/',views.SignUp,name='signup'),
	path('137/', UnitEntry.as_view(), name='unit'),
	path('808/', DataEntry.as_view(), name='dataentry'),
	path('', DataListView.as_view(), name='datalist'),
	path('110', views.login_page, name='log'),
	path('rotr/', router.as_view(), name='router'),
]

professional/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import CharField

# Create your models here.
class prodir(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name=models.CharField(max_length=40)
    jobsector=models.CharField(max_length=40)
    phone=models.BigIntegerField()
    workplace=models.CharField(max_length=40)
    reg_status=models.CharField(max_length=50)
    pr_status=models.CharField(max_length=50)


    def __str__(self):
        return self.name

class unitdata(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    name1=models.CharField(max_length=40)
    district=models.CharField(max_length=30)
    zone=models.CharField(max_length=40)
    unit=models.CharField(max_length=40)

    def __str__(self):
        return self.name1

professional/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


REG_CHOICE=(
    ('NOTHING','NOT REGISTERED'),
    ('ALONE','REGISTERED ALONE'),
    ('FAMILY','REGISTERED WITH FAMILY'),
    ('FRIENDS', 'REGISTERED WITH FRIENDS'),
    ('ONLINE', 'REGISTERED BUT VIEW ONLINE'))

PR_CHOICE=(
    ('INSTALLED','INSTALLED'),
    ('NOT','NOT INSTALLED'),
    ('ALREADY', 'ALREADY INSTALLED'))

# class BasicForm(UserCreationForm):
    
#     class Meta:
#         model=User
#         fields=['username', 'password1','password2']

#         # def clean(self):
#         #     if User.objects.filter(username=self.cleaned_data['username']).exists():
#         #         raise forms.ValidationError("Username is not unique")
        
#         # def __init__(self,*args,**kwargs):
#         #     super().__init__(*args,**kwargs)
#         #     self.fields['username'].label = 'User ID'


class Loginform(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput)




class Unit(forms.ModelForm):
    class Meta:
        model=unitdata
        fields=['name1', 'district', 'zone', 'unit']
        labels={
            'name1':'NAME',
            'district' : 'DISTRICT',
            'zone':'ZONE',
            'unit':'UNIT',
        }

class ProForm(forms.ModelForm):
    class Meta:
        model=prodir
        fields=[
            'name', 'jobsector', 'phone', 'workplace'
        ]
        # widgets={
        #     'reg_status':forms.Select(choices= REG_CHOICE), 
        #     'pr_status':forms.Select(choices = PR_CHOICE),
        #     }

professional/views.py
from django.contrib.auth import authenticate , login, logout
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import CreateView, View
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from .forms import *
from .models import * 
from django.contrib.auth.models import User, auth
from django.contrib.auth.mixins import LoginRequiredMixin

def SignUp(request):
    if request.method=='POST':
        usernm = request.POST['username']
        password =request.POST['password']
        print(usernm,password)
        if User.objects.filter(username=usernm).exists():
            form = User.objects.get(username=usernm)
            form.set_password(password)
            form.save()
            user = authenticate(request, username=usernm, password=password)
            if user is not None:
                login(request, user)
                return redirect('pro:datalist')
        else:
            new_user=User.objects.create_user(username=usernm,password=password,)
            new_user.save()
            user = authenticate(request, username=usernm, password=password)
            if user is not None:
                login(request, user)
                return redirect('pro:unit')


    return render(request, 'professional/signup.html')


class UnitEntry(LoginRequiredMixin, CreateView):
    login_url='pro:log'
    
    models=unitdata
    form_class=Unit
    template_name='professional/next.html'

    def post(self, request, *args, **kwargs):
        unitdata1=Unit(request.POST)
        if unitdata1.is_valid():
            conunit = unitdata1.save(commit=False)
            conunit.user = request.user
            conunit.save()
        return redirect('pro:datalist')




def login_page(request):
    if request.method=='POST':
        usernm=request.POST['username']
        psw=request.POST['password']
        user=auth.authenticate(username=usernm,password=psw)
        if user is not None:
            auth.login(request,user)
            return redirect('pro:datalist')
    return render(request,'professional/login.html')

class DataEntry(LoginRequiredMixin, CreateView):
    login_url='pro:log'

    model = prodir
    form_class = ProForm
    template_name='professional/update.html'
    # fields = ['name', 'jobsector', 'phone', 'panchayat', 'reg_status', 'pr_status']

    def post(self, request, *args, **kwargs):
        prodat=ProForm(request.POST)
        if prodat.is_valid():
            cal = prodat.save(commit=False)
            cal.user = request.user
            cal.save()
        return redirect('pro:datalist')


class DataListView(LoginRequiredMixin, ListView):
    login_url='pro:log'

    model=prodir
    paginate_by=30
    template_name='professional/list.html'

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class router(LoginRequiredMixin, TemplateView):
    login_url='pro:log'

    template_name = 'professional/router.html'

professional/templates/professional/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>PROFESSIONAL DIRECTORY</title>

</head>
<body>
  <nav class="navbar navbar-light bg-light sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">WISDOM YOUTH</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">PROFESSIONAL DIRECTORY</h5>
          <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">My Profile</a>
            </li>
            
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
               Reports
              </a>
              <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
                <li><a class="dropdown-item" href="#">Unit Report</a></li>
                <hr class="dropdown-divider">
                <li><a class="dropdown-item" href="#">Zonal Report</a></li>
                <hr class="dropdown-divider">
                <li>
                  <li><a class="dropdown-item" href="#">District Report</a></li>
                <!-- <hr class="dropdown-divider"> -->
                <!-- <li><a class="dropdown-item" href="#">Something else here</a></li> -->
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Register</a>
            </li>
          </ul>
          <!-- <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form> -->
        </div>
      </div>
    </div>
  </nav>
    <div class="container">
        <div class="row">
          <div class="col">
            <img src="{% static '/professional/images/youth.png' %}" class="img-fluid" alt="form">
          </div>
          </div>
          <div class='row'>
          <div class="col">
          
              <div class="btn-group" role="group" aria-label="Basic example">
                <!-- <a href="{% url 'pro:router' %}"><button type="button" class="btn btn-primary">HOME</button></a>
                <a href="{% url 'cal:DataList' %}"><button type="button" class="btn btn-primary">CALLING PORTAL</button></a> -->
                <!-- <a href="{% url 'pro:datalist' %}"><button type="button" class="btn btn-primary">PROFESSIONAL DIR</button></a> -->
          </div>
      
        </div></div>
        <div class="row">
        <div class="col">
          <div class="col-8">
            <h3 class="mt-2">PROFESSIONAL DIRECTORY</h3>
            <hr class="mt-0 mb-4">
          <br>
          {% block content %}
          


          {% endblock %}
          </div>
          </div>
        </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

professional/templates/professional/list.html
{% extends 'professional/base.html' %}

{% block content %}
<table>
    <a href="{% url 'pro:dataentry' %}"><button type="button" class="btn btn-success">ADD NEW PERSON</button></a>
    <div class="table-responsive-xxl">
    <table class="table">
        <thead class="table-dark">
        <tr>
            <!-- <th>SL NO.</th> -->
            <th>NAME</th>
            <th>JOB_SECTOR</th>
            <th>PHONE</th>
            <th>LOCATION</th>
        </tr>
        </thead>
        <!-- Iterate over object_list -->
        {% for object in object_list %}
    
        <!-- Display Objects -->
       <tbody>
        <tr>
            
            <td><a href="{{object.get_absolute_url}}">{{ object.name }}</a></td>
            <td>{{ object.jobsector }}</td>
            <td>{{ object.phone }}</td>
            <td>{{ object.workplace }}</td>
            

        </tr>
        </tbody>

        <!-- If objet_list is empty  -->
        {% empty %}
        <li>No entries yet, please add new entry</li>
        {% endfor %}
  </table>
  </form>
  <div>
    {% for message in messages %}
    <h3 style="color: black;">{{message}}</h3>
    {% endfor %}
  </div>  
{% endblock %}

professional/templates/professional/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>WISDOM YOUTH</title>

</head>
<body>
    <div class="container">
        <div class="row">
          <div class="col">
            <img src="{% static '/professional/images/youth.png' %}" class="img-fluid" alt="form">
          </div>
          </div>
          <div class='row'>
          <div class="col">
          
              <div class="btn-group" role="group" aria-label="Basic example">
                <!-- <a href="{% url 'pro:router' %}"><button type="button" class="btn btn-primary">HOME</button></a>
                <a href="{% url 'cal:DataList' %}"><button type="button" class="btn btn-primary">CALLING PORTAL</button></a> -->
                <!-- <a href="{% url 'pro:datalist' %}"><button type="button" class="btn btn-primary">PROFESSIONAL DIR</button></a> -->
          </div>
      
        </div></div>
        <div class="row">
        <div class="col">
          <div class="col-8">
            <h3 class="mt-2">PROFESSIONAL DIRECTORY</h3>
            <hr class="mt-0 mb-4">
          <br>
<table>
  <form action={% url 'pro:log' %} method="post">
    {% csrf_token %}
      <div class="form-floating mb-3">
      <input type="number" name="username" placeholder="phone_number" required></div>
      <div class="form-floating mb-3">
      <input type="password" name="password" placeholder="password" required></div>
      
      <button type="submit" name='save' class="btn btn-success">Log In</button></br></br>
      <a href="{% url 'pro:signup' %}"><button type="button" class="btn btn-success">New/Password Change</button></a>
      </form>
      <div></table>
    {% for message in messages %}
    <h3 style="color: black;">{{message}}</h3>
    {% endfor %}
  </div>  
</div>
</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

professional/templates/professional/next.html
{% extends 'professional/base.html' %}

{% block content %}
<table>
  <form method="post">
    {% csrf_token %}
   {{ form.as_table }}
  </table>
    <button type="submit" name='save' class="btn btn-success">Next</button>
    <a href="{% url 'pro:datalist' %}"><button type="button" class="btn btn-success">Cancel</button></a>
  </form>
  <div>
    {% for message in messages %}
    <h3 style="color: black;">{{message}}</h3>
    {% endfor %}
  </div>  
{% endblock %}

professional/templates/professional/router.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>WISDOM YOUTH</title>

</head>
<body>
    <div class="container">
      <div class="row">
        <div class="col">
          <img src="{% static 'professional/images/youth.png' %}" class="img-fluid" alt="form">
        </div>
        </div>

          <div class='row'>
          <div class="col">
          
              <div class="btn-group" role="group" aria-label="Basic example">
              <!-- <a href="{% url 'pro:router' %}"><button type="button" class="btn btn-primary">HOME</button></a>
              <a href="{% url 'cal:DataList' %}"><button type="button" class="btn btn-primary">CALLING PORTAL</button></a> -->
              <a href="{% url 'pro:datalist' %}"><button type="button" class="btn btn-primary">PROFESSIONAL DIR</button></a>
          </div>
      
        </div></div>
        </div>
        </body>
        </html>

professional/templates/professional/signup.html
{% extends 'professional/base.html' %}

{% block content %}

    <form action="{% url 'pro:signup' %}" method="post">
    {% csrf_token %}
    <div class="form-floating mb-3">
    <input type="number" name="username" placeholder="phone_number" required></div>
    <div class="form-floating mb-3">
    <input type="password" name="password" placeholder="password" required></div>

    <button type="submit" class="btn btn-success">Sign Up</button>
    <a href="{% url 'pro:log' %}"><button type="button" class="btn btn-success">Cancel</button></a>
  </form>
  <div>
    {% for message in messages %}
    <h3 style="color: black;">{{message}}</h3>
    {% endfor %}
  </div>  
{% endblock %}

professional/templates/professional/update.html
{% extends 'professional/base.html' %}

{% block content %}
<table>
  <form method="post">
    {% csrf_token %}
   {{ form.as_table }}
  </table>
    <button type="submit" name='save' class="btn btn-success">Update</button>
    <a href="{% url 'pro:datalist' %}"><button type="button" class="btn btn-success">Cancel</button></a>
  </form>
  <div>
    {% for message in messages %}
    <h3 style="color: black;">{{message}}</h3>
    {% endfor %}
  </div>  
{% endblock %}