dashboard/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'dash'

urlpatterns = [
	path('main/',HomePageView.as_view(),name='das1'),
    # path('spouse/',SpousePageView.as_view(),name='das2'),
    path('csv', views.export_registrations_xls, name='export_registrations_xls'),
    path('csv2', views.export_spouse_xls, name='export_spouse_xls'),
    path('csv3', views.export_childrens_xls, name='export_childrens_xls'),
    path('csv4', views.export_pdir_xls, name='export_pdir_xls'),
    path('csv5', views.export_unit_xls, name='export_unit_xls'),
]

home/urls.py
from django.urls import path

from . import views

app_name= 'reg' 
urlpatterns = [
	path('',views.regs,name=''),
	path('spouse/',views.further,name='spouse'),
	path('child/',views.studs,name='child'),
	path('thanks/', views.thanks, name='success'),
	path('pay/', views.pay, name='pay'),

]

proface/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

import professional

urlpatterns = [
    path('das/', include('dashboard.urls')),
    path('', include('professional.urls')),
    path('home/',include('home.urls')),
    path('cal/',include('calportal.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns=urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.views import generic
from professional.models import prodir, unitdata
from home.models import *
from django.contrib.auth.models import User
import csv

# Create your views here.

class HomePageView(generic.ListView):
    # model:regddd
    template_name='dashboard/report1.html'
    context_object_name='registrants_dat'

    def get_queryset(self):
        return regddd.objects.order_by('district')

# class SpousePageView(generic.ListView):
#     # model:regddd
#     template_name='dashboard/report2.html'
#     context_object_name='spouse_dat'

#     def get_queryset(self):
#         return regddd.objects.order_by('district')

def export_registrations_xls(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="registration_data.xls"'

    registrants = regddd.objects.order_by('district')
    writer = csv.writer(response)  
    for registrant in registrants:
        writer.writerow([registrant.district, registrant.user.first_name,  registrant.job,registrant.user.username, registrant.place,])
        

    return response 

def export_spouse_xls(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="spouse_data.xls"'

    registrants = wife.objects.order_by('nm')
    writer = csv.writer(response)  
    for registrant in registrants:
        # writer.writerow([registrant.district, registrant.user.wife.nm,  registrant.user.wife.ph,registrant.user.first_name])
        writer.writerow([registrant.user.username, registrant.user.regddd.district, registrant.user.wife.nm, registrant.user.first_name ])

    return response 

def export_childrens_xls(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="childrens_data.xls"'

    registrants = st.objects.order_by('nm')
    writer = csv.writer(response)  
    for registrant in registrants:
        # writer.writerow([registrant.district, registrant.user.wife.nm,  registrant.user.wife.ph,registrant.user.first_name])
        writer.writerow([registrant.user.username, registrant.user.regddd.district, registrant.nm, registrant.age, registrant.user.first_name ])

    return response 

def export_pdir_xls(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="professional_directory_data.xls"'

    registrants = prodir.objects.order_by('name')
    writer = csv.writer(response)  
    writer.writerow(['username', 'name', 'jobsector', 'phone', 'workplace',])
    for registrant in registrants:
        # writer.writerow([registrant.district, registrant.user.wife.nm,  registrant.user.wife.ph,registrant.user.first_name])
        writer.writerow([registrant.user.username, registrant.name, registrant.jobsector, registrant.phone, registrant.workplace,])

    return response 

def export_unit_xls(request):
    response = HttpResponse(content_type='unit/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="unit_data.xls"'

    registrants = unitdata.objects.order_by('name1')
    writer = csv.writer(response)  
    writer.writerow(['username', 'name', 'district', 'zone', 'unit', 'phone'])
    for registrant in registrants:
        # writer.writerow([registrant.district, registrant.user.wife.nm,  registrant.user.wife.ph,registrant.user.first_name])
        writer.writerow([registrant.user.username, registrant.name1, registrant.district, registrant.zone, registrant.unit,])

    return response 
    

dashboard/templates/dashboard/report1.html
{% extends 'professional/base.html' %}

{% block content %}
<!-- <a href="{% url 'dash:export_registrations_xls' %}">Export</a> -->
<a href="{% url 'dash:export_registrations_xls' %}"><button type="button" class="btn btn-success">General Export</button></a>
<a href="{% url 'dash:export_spouse_xls' %}"><button type="button" class="btn btn-success">Spouse Export</button></a>
<a href="{% url 'dash:export_childrens_xls' %}"><button type="button" class="btn btn-success">Children Data</button></a>
<a href="{% url 'dash:export_pdir_xls' %}"><button type="button" class="btn btn-success">Professional Dir</button></a>
<a href="{% url 'dash:export_unit_xls' %}"><button type="button" class="btn btn-success">UnitDir</button></a>

{% if registrants_dat %}
<table>
    <div class="table-responsive-xxl">
        <table class="table">
            <thead class="table-dark">
            <tr>
                <th>SL.No</th>
                <th>DISTRICT</th>
                <th>NAME</th>
                <th>PROFESSION</th>
                <th>PHONE</th>
                <th>LOCATION</th>
            </tr>
            {% for reg in registrants_dat %}
            <tr>
                <td>{{ forloop.counter}}</td>
                <td>{{ reg.district}}</td>
                <td>{{ reg.user.first_name}}</td>
                <td>{{ reg.job}}</td>
                <td>{{ reg.user.username}}</td>
                <td>{{ reg.place}}</td>
            </tr>
            {% endfor %}
                <p>{{ forloop.counter}}.{{ reg.district }} &emsp; {{ reg.user.first_name }}  &emsp; {{ reg.user }}  &emsp; {{ reg.user.unitdata.name1 }}</p>
</table>
{% endif %}
{% endblock %}

dashboard/templates/dashboard/report2.html
{% extends 'professional/base.html' %}
{% block content %}
{% if spouse_dat %}
<table>
    <div class="table-responsive-xxl">
        <table class="table">
            <thead class="table-dark">
            <tr>
                <th>SL.No</th>
                <th>DISTRICT</th>
                <th>NAME</th>
                <th>PROFESSION</th>
                <th>PHONE</th>
                <th>LOCATION</th>
                {% counter = 1%}
            </tr>
            {% for reg in spouse_dat %}
            {% if reg.ct == 'married' %}
            <tr>
                <td>{{ counter}}</td>
                <td>{{ reg.district}}</td>
                <td>{{ reg.user.wife.nm}}</td>
                <td>{{ reg.user.wife.pro}}</td>
                <td>{{ reg.user.wife.phone}}</td>
                <td>{{ reg.user.wife.children}}</td>
                {% counter++ %}
            </tr>
            {% endif %}
            {% endfor %}
                <!-- <p>{{ forloop.counter}}.{{ reg.district }} &emsp; {{ reg.user.first_name }}  &emsp; {{ reg.user }}  &emsp; {{ reg.user.unitdata.name1 }}</p> -->
</table>
{% endif %}
{% endblock %}